# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Install required packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends wget procps x11-apps xvfb openbox && \
    apt-get clean && \
    mkdir -p /usr/share/man/man1 && \
    mkdir -p /usr/lib/jvm && \
    wget -qO- https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz | tar xz -C /usr/lib/jvm && \
    update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-11.0.2/bin/java 100 && \
    update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk-11.0.2/bin/javac 100

# Set JAVA_HOME environment variable
ENV JAVA_HOME=/usr/lib/jvm/jdk-11.0.2

# Copy MySQL connector JAR file into the container
COPY docker/mysql-connector/mysql-connector-j-8.0.33.jar /usr/local/spark/jars/

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Copy the scripts directory into the container at /app/scripts
COPY scripts/ /app/scripts/

# Copy the .env file into the container at /app
COPY .env .env

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["python", "scripts/python/app.py"]
