# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

COPY scripts/ scripts/
COPY data/ data/
COPY .env .env

# Expose application port
EXPOSE 5000

# Start application
CMD ["python", "scripts/your_script.py"]
