# Base image
FROM openjdk:8-jdk-slim

# Set environment variables
ENV SPARK_VERSION=3.1.2
ENV HADOOP_VERSION=3.2
ENV SPARK_HOME=/opt/spark

# Install Spark
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://archive.apache.org/dist/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz && \
    tar -xzf spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz -C /opt && \
    mv /opt/spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION $SPARK_HOME && \
    rm spark-$SPARK_VERSION-bin-hadoop$HADOOP_VERSION.tgz

# Set environment variables for Spark
ENV PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin

# Expose Spark ports
EXPOSE 4040 7077 8080 18080

# Start Spark services
CMD ["sh", "-c", "start-master.sh && tail -f /dev/null"]
